[versions]

activityKtxVersion = "1.9.1"
agpVersion = "8.9.1"
appcompatVersion = "1.7.0"
constraintlayoutVersion = "2.1.4"
converterGsonVersion = "2.3.0"
coreKtxVersion = "1.13.1"
diskRestapiSdkVersion = "1.03"
fragmentKtxVersion = "1.8.2"
kotlinVersion = "1.9.20"
lifecycleExtensionsVersion = "2.2.0"
loggingInterceptorVersion = "4.6.0"
materialVersion = "1.12.0"
recyclerviewVersion = "1.3.2"
retrofitVersion = "2.4.0"
rxandroidVersion = "2.0.1"
rxjavaVersion = "2.2.19"
rxkotlinVersion = "2.4.0"

[libraries]

androidx-activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtxVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtxVersion" }
androidx-lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensionsVersion" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }

kotlin-kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }

material = { module = "com.google.android.material:material", version.ref = "materialVersion" }

okhttp3-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit-adapterRxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofitVersion" }
retrofit-converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }

yandex-diskRestapiSdk = { module = "com.yandex.android:disk-restapi-sdk", version.ref = "diskRestapiSdkVersion" }

androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agpVersion" }
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }

rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjavaVersion" }
rxjava-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroidVersion" }
rxjava-rxkotlin = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rxkotlinVersion" }

[plugins]
